export const GET_DATA = 'get_data'
export const GET_LOGIN = 'get_login'
export const GET_BORROW = 'get_borrow'
export const OUT_LOGIN = 'out_login'
export const BW_RENEW = 'bw_renew'
export const NEW_FRESH = 'new_fresh'
